language: ruby
cache: bundler
rvm:
  - 2.1.5

addons:
  postgresql: "9.3"

before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script: "bundle exec rspec"
